config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  root 'pages#index'
  
  get 'searches/show', to: 'searches#show'
  
  get 'users/new_manager'
  
  resources :users
  resources :account_activations, only: [:edit]
  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #get 'communities/new'
  resources :communities
  # params[:id] <== 有効化トークン入れる
  # Controller: params[:id]
  
  resources :invitations
  
  get 'mains/index'
  
  get 'comments/new'
  
  get 'settings/new'
  
  get 'schedules/calender'
  
  get 'tests/test1'
  get 'tests/test2'
  get 'tests/test3'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories
  
end

app/models/channel.rb
class Channel < ApplicationRecord
end

app/models/community.rb
class Community < ApplicationRecord
  validates :communityName, presence: true, uniqueness: true
  validates :category, presence: true
  validates :subcategory, presence: false
  validates :prefecture, presence: true
  validates :sex, presence: false
  validates :scale, presence: false
  validates :image, presence: false
  validates :description, length: { maximum: 255 }
  validates :user_id, presence: true
  validates :public, presence: true
  
  has_many :users
end

app/models/gthread.rb
class Gthread < ApplicationRecord
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  validates :family_name, presence: true, length: { maximum: 15 }
  validates :first_name, presence: true, length: { maximum: 15 }
  validates :email, presence: true#, uniqueness: true
  #, format: { with: /\A[A-Za-z0-9._+]+@[A-Za-z]+\.[A-Za-z]+\z/ }
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    #format: { with: VALID_EMAIL_REGEX },
                    #uniqueness: { case_sensitive: false }
  validates :user_id, presence: true
  
  belongs_to :user
  
  # サイト招待用のメールを送信する
  def send_invitation_email
    UserMailer.invitation(self).deliver_now #()内の@inviteeを => self に
  end
  
  private
    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = self.email.downcase
    end
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  validates :role, presence: true
  validates :family_name, presence: true, length: { maximum: 15 }
  validates :first_name, presence: true, length: { maximum: 15 }
  validates :accountName, presence: true
  validates :email, presence: true#, uniqueness: true
  #, format: { with: /\A[A-Za-z0-9._+]+@[A-Za-z]+\.[A-Za-z]+\z/ }
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    #format: { with: VALID_EMAIL_REGEX },
                    #uniqueness: { case_sensitive: false }
  
  has_secure_password
  #PW_REGEX = /\A(?=.?[a-z])(?=.?\d)[a-z\d]{8,20}+\z/i  ⬅️テストユーザー作成時のパスを簡単にするため
  #validates :password, format: {with: PW_REGEX}
  
  validates :image, presence: false
  validates :description, presence: false, length: { maximum: 255 }
  validates :remember_digest, presence: false
  
  has_many :communities
  has_many :roles
  has_many :invitations
  
  
  attr_accessor :remember_token, :activation_token #インスタンスメソッドremember_token, activation_tokenの
                                                   #セッターとゲッターを一括指定
  
  #＜永続的ログイン機能＞
  before_save   :downcase_email
  # 有効化トークンや有効化ダイジェストはユーザーオブジェクトが作成される前に作成しておく必要がある
  before_create :create_activation_digest
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token #インスタンスメソッドのremember_token(24行目)が呼ばれる
    update_attribute(:remember_digest, User.digest(remember_token)) #記憶ダイジェストの更新
  end
  
  # 渡されたトークンがremember（もしくはアカウント有効化）ダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)   # attributeにrememberかactivateが入る
    digest = send("#{attribute}_digest") # モデルの属性である〜_digestにアクセス
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  #＜ユーザー有効化メソッド＞
  # アカウントを有効にする
  def activate
    #update_attribute(:activated,    true)
    #update_attribute(:activated_at, Time.zone.now)
    #                   ⬇️
    update_columns(activated: FILL_IN, activated_at: FILL_IN)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now #()内の@userを => self に
  end
  
  private
    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = self.email.downcase
    end
    
    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
      # @user.activation_digest => ハッシュ値が入る
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def index
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def test1
  end
  
  def test2
  end
  
  def test3
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    @user.role = 1
    @user.image = nil
    @user.description = nil
    @user.remember_digest = nil
    #binding.pry
    if @user.save
      @user.send_activation_email
      redirect_to root_url, success: 'メールを送信しました'
    else
      flash.now[:danger] = "メール送信に失敗しました"
      render :new
    end
  end
  
  def new_manager
  end
  
  def index
    # 有効化されたユーザーのみ表示される
    @users = User.where(activated: FILL_IN).paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    redirect_to root_url #and return unless FILL_IN
  end
  
  def edit
    @users = User.find(params[:id])
  end
  
  private
    def user_params
      params.require(:user).permit(:family_name, :first_name, :accountName, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #include CommonActions
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # ユーザーのセッションを永続的にする
  #def remember(user)
  #  user.remember
  #  cookies.permanent.signed[:user_id] = user.id
  #  cookies.permanent[:remember_token] = user.remember_token
  #end
  
  
  
  # 永続的セッションを破棄する
  #def forget(user)
  #  user.forget
  #  cookies.delete(:user_id)
  #  cookies.delete(:remember_token)
  #end
  
  # 現在のユーザーをログアウトする
  #def log_out
  #  forget(current_user)
  #  session.delete(:user_id)
  #  @current_user = nil
  #end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'd_custom', media: 'screen and (min-width: 1200px)', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    't_custom', media: 'screen and (min-width: 768px) and (max-width: 1199px)', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'm_custom', media: 'screen and (max-width: 767px', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- drawer.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/css/drawer.min.css">
    <!-- jquery & iScroll -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.2.0/iscroll.min.js"></script>
    <!-- drawer.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/js/drawer.min.js"></script>
    <!-- popper.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.js"></script>
    <!-- dropdown.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <!-- Font Awesome5 アニメーションを使用するためのコード -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert">
        <%= value %>
      </div>
    <% end %>
    
    <%= yield %>
    <script>
      // アラート
      $(function(){
        $(".alert").fadeOut(4000);
      });
      
      // Drawer
      $(document).ready(function() {
        $('.drawer').drawer();
      });
      
      $('.dropdown-toggle').dropdown();
      
      $('.drawer').drawer({
        class: {
          nav: 'drawer-nav',
          toggle: 'drawer-toggle',
          overlay: 'drawer-overlay',
          open: 'drawer-open',
          close: 'drawer-close',
          dropdown: 'drawer-dropdown'
        },
        iscroll: {
          // Configuring the iScroll
          // https://github.com/cubiq/iscroll#configuring-the-iscroll
          mouseWheel: true,
          preventDefault: false
        },
        showOverlay: true
      });
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-wrapper text-center">
  <%#div class="container-fluid"%>
    <div class="top-container">
      <h1 class="text-black">サイト名</h1>
      <div class="row">
        <div class="offset-xl-2 offset-lg-2 offset-md-1 offset-1 col-xl-3 col-lg-3 col-md-4 col-4" id="resizebutton1">
          <%= link_to 'サインアップ', new_user_path, class: 'btn btn-block btn-black btn-outline-info' %>
        </div>
        <div class="offset-xl-2 offset-lg-2 offset-md-2 offset-2 col-xl-3 col-lg-3 col-md-4 col-4" id="resizebutton2">
          <%= link_to 'ログイン', login_path, class: 'btn btn-block btn-black' %>
        </div>
      </div>
      <div class="public-com-container">
        <h2 class="text-black">コミュニティを探す</h2>
        <div class="row">
          <div class="offset-xl-2 offset-lg-2 offset-md-1 offset-1 col-xl-8 col-lg-8 col-md-10 col-10">
            <%= form_with url: '/', method: 'get' do %>
              <div class="input-group" id="resizebox">
                <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "キーワードから探す" %> <%# params[:search]をどうするか %>
                <span class="input-group-append">
                  <%= link_to '#', class: "btn btn-primary", method: :get do %>
                    <i class="fa fa-search"></i>
                  <% end %>
                </span>
              </div>
            <% end %>
          </div>
        </div>
        <div class="row text-right">
          <div class="offset-xl-2 offset-lg-2 offset-md-1 offset-1 col-xl-8 col-lg-8 col-md-10 col-10">
            <p1>
              <%= link_to '>>詳細検索する', searches_show_path, class: "text-black" %>
            </p1>
          </div>
        </div>
        <h3 class="text-black">人気の公開コミュニティ</h3>
        <div class="box_scrollbar" align="center">
          <table class="table table-hover">
            <tr class="table-light">
              <td width="6rem" align="center"><%#img src="./staff_01.jpg" class="community-image" class="img-thumbnail"%></td><td>F.L.Tクラブ</td>
            </tr>
            <tr class="table-light">
              <td align="center"><%#img src="./staff_02.jpg" class="community-image"%></td><td>Tech Boost</td>
            </tr>
            <tr class="table-light">
              <td align="center"><%#img src="./staff_02.jpg" class="community-image"%></td><td>こぶし</td>
            </tr>
            <tr class="table-light">
              <td align="center"><%#img src="./staff_02.jpg" class="community-image"%></td><td>ルクール</td>
            </tr>
            <tr class="table-light">
              <td align="center"><%#img src="./staff_02.jpg" class="community-image"%></td><td>Team Black</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  <%#</div>%>
</div>
<%= javascript_include_tag "pages_index_resize.js" %>